### ISSUE TITLE
Colorization on 1929 movie

### ISSUE THREAD

**Issue by ttoinou** [richzhang/colorization#15]
Hi

Thanks for this script ! I tried your colorization (v2 with class rebalancing) on some frames from Man With a Movie Camera (Vertov, 1929) here are the results : 
[https://drive.google.com/open?id=0B5-1OeNPsecwdTZ4dS0wUUhIaUU](url)

![man with a movie camera the cinematic orchestra soundtrack dvdrip_scene19_7655](https://cloud.githubusercontent.com/assets/12092576/20574999/96beb904-b1b7-11e6-9842-154bfc74ea33.jpg)
![man with a movie camera the cinematic orchestra soundtrack dvdrip_scene19_7655](https://cloud.githubusercontent.com/assets/12092576/20575013/a83d9d6c-b1b7-11e6-86e6-3a7174208fbe.jpg)

 * The results are all oranges :( what do you think I can do to have a better quality ?
 * Should I train my own network with frames from documentaries ?
 * Do you think I should start training from scratch or start from your network v2 ?
 * Could we introduce some kind of temporal consistency across a bunch of frames for movie colorization  ?

Thanks in advance !
Antoine.

**Comment by richzhang** [comment]
Our network is trained on modern photos, so there's a domain gap when applied to old movies. I think training your own network with old color movies is a great idea and can help bridge that gap. I would recommend starting from our network and fine-tuning on old movies.

Yes, temporal consistency would also make the results look nicer.

**Comment by ttoinou** [comment]
Thank you for your input, I'm first going to extract color frame from movies and documentaries. If I need ~500k iterations how many iter/images ? (not 1 I suppose)

**Comment by ttoinou** [comment]
I've extracted 12k frames from movies, now I need to create an LMDB file, do you think that tutorial would work [http://deepdish.io/2015/04/28/creating-lmdb-in-python/](url) ?
Sorry for the noob question

**Comment by theColourSpace** [comment]
Hi ttoinou,

I'm also trying to use this engine for colorization on some historical images. Would have any interest in collaborating on this?

**Comment by ttoinou** [comment]
Hi, yes of course ! 
There's also another software for colorization : https://github.com/gustavla/autocolorize 
But I didn't succeed in installing it (yet)

**Comment by ttoinou** [comment]
My email : tit_toinou@hotmail.com

**Comment by ttoinou** [comment]
If anyone want to process an entire folder he can use my script : https://github.com/ttoinou/colorization/blob/master/color.py
