### ISSUE TITLE
Anaconda Windows

### ISSUE THREAD

**Issue by Ratinod** [richzhang/colorization#17]
Hello.
I'm trying to start "colorization" on windows.
Since the beginning I have successfully launched a "Deep Dream". ( [Using this manual](http://thirdeyesqueegee.com/deepdream/2015/07/19/running-googles-deep-dream-on-windows-with-or-without-cuda-the-easy-way/) ).  But when you try to use the same method "colorization" I can't run it successfully. 
On a piece of code (probably) 
`net = caffe.Net('../models/colorization_deploy_v2.prototxt', '../models/colorization_release_v2.caffemodel', caffe.TEST)` 
Python just crash...
I tried everything I could and I do not know where there may be a problem.
Please, I need help. And I am sorry that I ask it in here. I do not know where else I can ask for help.

--Update--

Error: [imgur](http://imgur.com/G3LSFyG)

**Comment by richzhang** [comment]
Unfortunately, I don't have expertise on caffe for windows. The [caffe-users-group](https://groups.google.com/forum/#!forum/caffe-users) may be able to help.
