### ISSUE TITLE
Inconsistency between code and paper

### ISSUE THREAD

**Issue by grgvineet** [richzhang/colorization#18]
In paper the loss is defined as :
`L = - sum( v * sum(Z * log(Z_cap) ) ),`
where we can take advantage of Python broadcasting and can write it as
`L = -sum( v * Z * log(Z_cap) )`

where as in code conv8_313_boost layer, which is `ClassRebalanceMultLayer` layer, bottom blob is passed as it is. Which makes the loss:
`L = -sum( Z * log(Z_cap) )`

Considering even commented code which is
`top[0].data[...] = bottom[0].data[...]*bottom[1].data[...] `
where `bottom[0]` can be considered as Z_cap, and `bottom[1]` can be considered as `v`.
Due to this, the loss will be computed as :
`L = -sum( Z * log( v * Z_cap) )`
Is it intentional ?

Also in `ClassRebalanceMultLayer`, forward pass is not doing anything, but backward pass is boosting gradients according to weighting terms. Can you explain the logic behind this ?

**Comment by richzhang** [comment]
Good catch. The implementation for the class rebalancing is a bit of a hack. The forward loss shown isn't computed with the class-rebalancing. However, the gradient going back is rebalanced, so it is actually minimizing the class-rebalanced loss in the paper.
