### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by tzatter** [richzhang/colorization#2]
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 213:13: Message type "caffe.ConvolutionParameter" has no field named "dilation".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0402 13:04:55.491230 21321 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: colorization_deploy_v0.prototxt
*** Check failure stack trace: ***

Ubuntu14.04 GTX9602G
I installed NVIDIA's caffe following the steps below
https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md

Thank you richzhang

**Comment by richzhang** [comment]
Hi, dilation is a pretty recent feature, so you will need to clone the latest version of caffe and reinstall: https://github.com/BVLC/caffe

Happy colorizing!

**Comment by tzatter** [comment]
It works!
I am going to colorize my grandmother's old pictures

**Comment by liuweinudt** [comment]
HI,Rich zhang:
   I cloned `the latest version of caffe and still get the same result as "[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 213:13: Message type "caffe.ConvolutionParameter" has no field named "dilation"."`.
   I am using jupyter notebook on the server and chrome browser on the client. Could you give me any suggestion?Thanks.

**Comment by gmt710** [comment]
BVLC/caffe is ok.
