### ISSUE TITLE
typo in solver file

### ISSUE THREAD

**Issue by AruniRC** [richzhang/colorization#25]
The solver file `./train/solver.prototxt` has a typo that causes it to fail:

> Error parsing text-format caffe.SolverParameter: 5:1: Invalid value for boolean field "test_initialization". Value: "False".

The problem is a capitalised "false":

`test_initialization: False # don't run validation when loading`

This should be *false* not *False*.

**Comment by richzhang** [comment]
Thanks, fixed.
