### ISSUE TITLE
crash on the final step

### ISSUE THREAD

**Issue by imcaspar** [richzhang/colorization#3]
after set up  Caffe ( all test passed) and other requirement,
when I running to the final step( (3) Colorization time part ) in colorization_demo_v0.ipynb

python always crash. ("Python quit unexpectedly.")
then I try to run the script without ipython notebook, got the following error:
......
I0406 20:55:53.224961 1960824832 net.cpp:219] conv3_2 does not need backward computation.
I0406 20:55:53.225069 1960824832 net.cpp:219] relu3_1 does not need backward computation.
I0406 20:55:53.225086 1960824832 net.cpp:219] conv3_1 does not need backward computation.
I0406 20:55:53.225095 1960824832 net.cpp:219] conv2_2norm does not need backward computation.
I0406 20:55:53.225101 1960824832 net.cpp:219] relu2_2 does not need backward computation.
I0406 20:55:53.225108 1960824832 net.cpp:219] conv2_2 does not need backward computation.
I0406 20:55:53.225116 1960824832 net.cpp:219] relu2_1 does not need backward computation.
I0406 20:55:53.225123 1960824832 net.cpp:219] conv2_1 does not need backward computation.
I0406 20:55:53.225131 1960824832 net.cpp:219] conv1_2norm does not need backward computation.
I0406 20:55:53.225138 1960824832 net.cpp:219] relu1_2 does not need backward computation.
I0406 20:55:53.225145 1960824832 net.cpp:219] conv1_2 does not need backward computation.
I0406 20:55:53.225152 1960824832 net.cpp:219] relu1_1 does not need backward computation.
I0406 20:55:53.225358 1960824832 net.cpp:219] bw_conv1_1 does not need backward computation.
I0406 20:55:53.225379 1960824832 net.cpp:219] input does not need backward computation.
I0406 20:55:53.225431 1960824832 net.cpp:274] Network initialization done.
I0406 20:55:53.444080 1960824832 upgrade_proto.cpp:66] Attempting to upgrade input file specified using deprecated input fields: colorization_release_v0.caffemodel
I0406 20:55:53.444106 1960824832 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.
W0406 20:55:53.444110 1960824832 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
F0406 20:56:02.908959 1960824832 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

Test on macbook pro with 2GB GPU memory, maybe it need more GPU memory?

**Comment by richzhang** [comment]
It takes 500MB in my machine. Do you have something in your GPU already perhaps?

You can also run the model in CPU mode by setting `caffe.set_mode_gpu()` before calling `net.forward()`. The model will of course be slower, at ~6 seconds per image instead of 100ms.

**Comment by imcaspar** [comment]
affter set caffe.set_mode_cpu(), it works well :-)
Awesome job!
