### ISSUE TITLE
Is it right when direct using bgr order in testing?

### ISSUE THREAD

**Issue by hengliusky** [richzhang/colorization#30]
Hi, I notice that the color channel order of the image data is different between training and testing. In training, there is explicit BGR->RGB conversion, while in testing the image is inputed and directly used for rgb2lab. This is different, why not also do BGR->RGB? is that right?

**Comment by richzhang** [comment]
During training, we assume the data is saved off as BGR. During testing, in the demo file, the image is loaded as RGB.

**Comment by hengliusky** [comment]
thanks!
