### ISSUE TITLE
puzzled on color conversion

### ISSUE THREAD

**Issue by hengliusky** [richzhang/colorization#31]
In some prototxt files, the layer "ColorConv" is used to deal with rgb->lab. But in other prototxt files, the python code "color.rgb2lab" take the place. why do not use the same way? In addition,  the layer ColorConv" can not be found in normal Caffe version. what the data type (0-1,or 0-255) should be used when adopting ColorConv?

**Comment by azshue** [comment]
Hi, I am having the same problem here. Could you please tell me how you solved it? Thanks~
