### ISSUE TITLE
wget command not found

### ISSUE THREAD

**Issue by impactcolor** [richzhang/colorization#35]
When running fetch_release_models.sh in models directory I get the above error.
I also went to the referenced urls in the file and they are not present on the website.

These are the links that file is referencing: 
wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2.caffemodel -O ./models/colorization_$
wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2_norebal.caffemodel -O ./models/color$
wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v1/colorization_release_v1.caffemodel -O ./models/colorization_$

**Comment by fervi** [comment]
I'm not dev, but it works for me

If you don't have wget, install it (on Linux) - on Debians:
sudo apt-get install wget

**Comment by richzhang** [comment]
It's possible that the Berkeley servers were down at that time. The files appear to be there for me now.
