### ISSUE TITLE
Can't find problem

### ISSUE THREAD

**Issue by yarik2720** [richzhang/colorization#4]
at start I see only alert: 
/home/yaroslav/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Net<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/yaroslav/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Blob<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
/home/yaroslav/caffe/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Solver<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \

but later kernel crashes with that error in console:
F0407 23:49:31.456502 20193 upgrade_proto.cpp:86] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: colorization_release_v0.caffemodel
*** Check failure stack trace: ***
2016-04-07 23:49:32.242 [NotebookApp] KernelRestarter: restarting kernel (1/5)

using cuda 7.5 and latest caffe from https://github.com/BVLC/caffe/

**Comment by richzhang** [comment]
Unfortunately I'm not too sure what's going on here. Perhaps you can consult the [Caffe users group](https://groups.google.com/forum/#!forum/caffe-users) or [Caffe Github site](https://github.com/BVLC/caffe). Thanks!
