### ISSUE TITLE
A very simple net to colorize B&W photos designed for deep learning beginners

### ISSUE THREAD

**Issue by microic** [richzhang/colorization#42]
We use a very simple model for colorizing B&W photos:
![](https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/model.png)

Following is the result using only 179 train samples, no transfer learning, no data augmentation
<table>
<tr><th>input</th><th>output</th></tr>	
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/marie_curie.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/output/marie_curie.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/carson.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/output/carson.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/turing.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/model_b/files/Predict/group2/64/output/turing.png" width="192px" /></td></tr>
</table>

To get a better result, simply increase the number and size of train samples, but which will take much more time to train
Following is the result using 645 train samples:
<table>
<tr><th>input</th><th>output</th></tr>	
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/luxun.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/luxun.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/chengmei.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/chengmei.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/leifeng.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/leifeng.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/carson.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/carson.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/marie_curie.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/marie_curie.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/turing.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/turing.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/franklin.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/franklin.png" width="192px" /></td></tr>
<tr><td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/nobel.png" width="192px" /></td>
<td><img src="https://github.com/microic/niy/raw/master/examples/colorizing_photos/dataset/files/Predict/group2/output/nobel.png" width="192px" /></td></tr>
</table>

https://github.com/microic/niy/blob/master/examples/colorizing_photos

**Comment by richzhang** [comment]
Cool!
