### ISSUE TITLE
Are the probabilities in prior_probs.npy smoothed with a Gaussian kernel?

### ISSUE THREAD

**Issue by mingo-x** [richzhang/colorization#47]
Hi,

I didn't find the code to generate the _prior_probs.npy_ file, so I decided to ask here. Are the probabilities in the _prior_probs.npy_ file raw empirical probabilities? Or are they smoothed probabilities?

Many thanks!

**Comment by richzhang** [comment]
Hi, they are smoothed with the same Gaussian used to compute soft targets during training.

**Comment by mingo-x** [comment]
Thank you very much for the timely reply!
