### ISSUE TITLE
Data Load Error

### ISSUE THREAD

**Issue by mike1808** [richzhang/colorization#5]
Hello, I am trying to run the demo but the code fails on the model load, here is the last lines of the log:
```
I0422 05:05:37.127264 11607 net.cpp:274] Network initialization done.
I0422 05:05:37.197033 11607 upgrade_proto.cpp:66] Attempting to upgrade input file specified using deprecated input fields: colorization_release_v0.caffemodel
I0422 05:05:37.197067 11607 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.
W0422 05:05:37.197072 11607 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
F0422 05:05:37.197129 11607 net.cpp:765] Check failed: target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompatible number of blobs for layer conv1_2norm
```

Here is the full log output if you need it. [Gist](https://gist.github.com/mike1808/e5f4c8932c4daa1a100d2a11f5d3df85)

I am using the latest Caffe with cuDNNv5 on Ubuntu 16.04. Also, my Caffe is compiled from this [PR](https://github.com/BVLC/caffe/pull/3919) for the cuDNNv5 support.

Update: I suppose that PR adds some breaking changes in the batch normalization (now, cuDNN do that) that raise this issue.

Update #2: I think, the issue in [this](https://github.com/BVLC/caffe/pull/3919#discussion-diff-60536601R26) change.

**Comment by richzhang** [comment]
Thanks for your interest in the code! Unfortunately, I'm not too sure what's going on. Perhaps consult with the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group for help.
