### ISSUE TITLE
A strange question about the difference between train and deploy in prototxt

### ISSUE THREAD

**Issue by Xinian** [richzhang/colorization#58]
Hi, Richard,
    I have some question about difference between
    ./colorization/model/colorization_deploy_v2.prototxt 
and 
   ./colorization/model/colorization_train_val_v2.prototxt

in the end of colorization_deploy_v2.prototxt , you setup such a layer :
# **********************
# ***** Decoding *****
# **********************
layer {
  name: "class8_ab"
  type: "Convolution"
  bottom: "class8_313_rh"
  top: "class8_ab"
  convolution_param {
    num_output: 2
    kernel_size: 1
    stride: 1
    dilation: 1
  }
}
but this layer seems not be trained in colorization_train_val_v2.prototxt , so I can not understand how it maps the 313x64x64 to 2x224x224 , could you tell me why does it work ?

Thank you very much

**Comment by richzhang** [comment]
It contains the 313 ab color bin centers, so each spatial location is multiplied by a 313x2 matrix, implemented as a 1x1 convolution.

**Comment by Xinian** [comment]
Did you means this: 
the predict procedure has finished in 
# 564th line in colorization_deploy_v2.prototxt
layer {
  name: "class8_313_rh"
  type: "Softmax"
  bottom: "conv8_313_rh"
  top: "class8_313_rh"
}
it produce a 56 x 56 x 313 blob, and it means 313 ab values distribute for every pixel in  56 x 56 spatial data.
The "decode" procedure is just a re-scale operator?
Thank you.
