### ISSUE TITLE
paths are incorrect in colorization/models/fetch_release_models.sh

### ISSUE THREAD

**Issue by ghost** [richzhang/colorization#63]
Paths are incorrect in the Instrurtibles .   colorization/models/fetch_release_models.sh

wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2.caffemodel -O ./models/colorization_release_v2.caffemodel
wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v2/colorization_release_v2_norebal.caffemodel -O ./models/colorization_release_v2_norebal.caffemodel
wget http://eecs.berkeley.edu/~rich.zhang/projects/2016_colorization/files/demo_v1/colorization_release_v1.caffemodel -O ./models/colorization_release_v1.caffemodel

**Comment by richzhang** [comment]
Sometimes the Berkeley servers go down. I converted the weights and models to PyTorch and hosted them on S3.
