### ISSUE TITLE
I still get the same error even using the latest caffe, please give some advice 

### ISSUE THREAD

**Issue by liuweinudt** [richzhang/colorization#7]
HI,Rich zhang:
I cloned the latest version of caffe and still get the same result as "[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 213:13: Message type "caffe.ConvolutionParameter" has no field named "dilation".".
I am using jupyter notebook on the server and chrome browser on the client. Could you give me any suggestion?Thanks.

**Comment by vzk** [comment]
I just ran the caffe model and it seems to run perfectly both on the CPU only and GPU only mode. Can you check if your caffe/pycaffe installation is k ?

**Comment by liuweinudt** [comment]
Thanks, I have run the code not using Notebook and IPython, It is OK now.
