### ISSUE TITLE
Colorization of satellite imagery

### ISSUE THREAD

**Issue by xTriixrx** [richzhang/colorization#82]
To whom it may concern,

I have tested out this on some black and white satellite imagery I web scrapped and I received some funky results. I can only assume that the current model being used wasn't given any data to train for this case. Would it be possible to create a separate model for this case specifically? I am aware NOAA provides sample data that could be used for training within the following 2 FTP urls: 'ftp://public.sos.noaa.gov/models/bm10000/4096/' and 'ftp://public.sos.noaa.gov/rt/true_color/4096/'. It would be nice to be able to have access to a satellite focused model, if this is at all possible please let me know and thanks for your time.

**Comment by richzhang** [comment]
Thanks for the question. Yes, it was trained on natural images.
