### ISSUE TITLE
Pretrained weights are inaccessible

### ISSUE THREAD

**Issue by IRDonch** [richzhang/colorization#86]
The URLs from which the code downloads the pre-trained models ([siggraph17-df00044c.pth](https://colorizers.s3.us-east-2.amazonaws.com/siggraph17-df00044c.pth), [colorization_release_v2-9b330a0b.pth](https://colorizers.s3.us-east-2.amazonaws.com/colorization_release_v2-9b330a0b.pth)) are no longer accessible. They now return HTTP 403 errors.

**Comment by therealzuc** [comment]
I have found the same issue. I can not access pre-trained models both for eccv16 and for siggraph17.

**Comment by richzhang** [comment]
Thanks for pointing this out! The s3 buckets accidentally went to private. They should be accessible now

**Comment by therealzuc** [comment]
Thank you for the quick response!

**Comment by IRDonch** [comment]
Thanks, I confirm that the URLs work again.

**Comment by Zamachi** [comment]
Hi, I don't know whether it's just me, or the issue still persists, but I still get 403 forbidden when trying to download pretrained weights(master branch).
