### ISSUE TITLE
Question regarding capability

### ISSUE THREAD

**Issue by rafajafar** [richzhang/colorization#9]
Hey guys! I am really impressed by this library. 

So I have a video fingerprinting technology (no, not histogram, perceptual identification) which is pretty freaking accurate to a high resolution of precision (10 seconds from the source video is enough to match). The only "weak point" I have is when color saturation is changed from the source video. 

Something I've always really wanted was a way to "normalize" the color. In fact, since my system works way better with color than black-and-white video, colorizing a black and white video would be awesome! This is something I _absolutely must_ play with.

The question I have that you may be able to answer is whether this would produce reasonably consistent results:
1. Take source image, copy it, make it black and white
2. Take source image, copy it, saturate the color a bit, make it black and white
3. Colorize the result of #1 
4. Colorize the result of #2 

When you compare those two, how similar are they? Assume reasonable saturation change so it does not harm the user perception of the original image too much.

If you know this off-hand, that'd be amazing! (I can't test right now)

--Collin

**Comment by richzhang** [comment]
Hi Collin, It sounds like you may want a white balancing algorithm. We are actually playing around with re-purposing our algorithm for white balancing, but don't have anything mature on it yet. Thanks for your interest!

Richard

**Comment by rafajafar** [comment]
Thanks! Yes, that is close, but consistency is the key and AWB's tend to vary depending on the illuminate pixel samples... making it very picture-dependent. What fascinated me about your system is it could have the effect  need without balancing at all, or perhaps only balancing a grayscale variant of the picture. 

If you do wind up implementing this, or even want someone to assist in testing, I would be interested. Do you have a prefered notification method for updating on progress of such things?

**Comment by richzhang** [comment]
Hi, you can check my [webpage](https://richzhang.github.io/) or my group members webpages (find them on here: https://people.eecs.berkeley.edu/~efros/) for our most recent work!

**Comment by collincusce** [comment]
Did you ever do anything with white balancing?

**Comment by richzhang** [comment]
We didn't end up pursuing that. We may get back to it at some point. Thanks!
